"""Add supplier payment and transaction models

Revision ID: 211c185ab9f6
Revises: dd496a1b855b
Create Date: 2025-12-30 20:00:06.737162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import text

# revision identifiers, used by Alembic.


def safe_drop_constraint(constraint_name: str, table_name: str, type_: str = None):
    """Drop constraint if it exists (safe for fresh installs)."""
    conn = op.get_bind()
    # Check if constraint exists before trying to drop
    result = conn.execute(text("""
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = :constraint_name
        AND table_name = :table_name
    """), {"constraint_name": constraint_name, "table_name": table_name})
    if result.fetchone():
        op.drop_constraint(constraint_name, table_name, type_=type_)


def safe_drop_index(index_name: str, table_name: str):
    """Drop index if it exists (safe for fresh installs)."""
    conn = op.get_bind()
    # Use DROP INDEX IF EXISTS for safety
    conn.execute(text(f"DROP INDEX IF EXISTS {index_name}"))
revision: str = '211c185ab9f6'
down_revision: Union[str, None] = 'dd496a1b855b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Enum('CASH', 'EFT', 'CHECK', 'PROMISSORY', 'PARTIAL', name='paymenttype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('transfer_code', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('serial_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('ORDER', 'PAYMENT', 'RETURN', 'ADJUSTMENT', name='transactiontype'), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('debt_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('running_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    safe_drop_index('ix_branches_organization_id', table_name='branches')
    safe_drop_index('ix_cdi_cash_difference_id', table_name='cash_difference_items')
    safe_drop_index('ix_cdi_platform_source', table_name='cash_difference_items')
    op.alter_column('cash_differences', 'kasa_visa',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'kasa_nakit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'kasa_trendyol',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'kasa_getir',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'kasa_yemeksepeti',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'kasa_migros',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'kasa_total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'pos_visa',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'pos_nakit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'pos_trendyol',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'pos_getir',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'pos_yemeksepeti',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'pos_migros',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'pos_total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('cash_differences', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'ok'::character varying"))
    safe_drop_index('ix_cash_differences_date', table_name='cash_differences')
    safe_drop_index('ix_cash_differences_status', table_name='cash_differences')
    safe_drop_constraint('uq_cash_diff_branch_date', 'cash_differences', type_='unique')
    op.create_index(op.f('ix_cash_differences_difference_date'), 'cash_differences', ['difference_date'], unique=False)
    op.alter_column('daily_insights', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    safe_drop_constraint('daily_insights_branch_id_date_key', 'daily_insights', type_='unique')
    safe_drop_index('ix_expense_categories_branch_id', table_name='expense_categories')
    safe_drop_constraint('expense_categories_branch_id_fkey', 'expense_categories', type_='foreignkey')
    op.create_foreign_key(None, 'expense_categories', 'branches', ['branch_id'], ['id'])
    safe_drop_index('ix_import_history_branch_date', table_name='import_history')
    safe_drop_index('ix_import_history_items_history', table_name='import_history_items')
    op.alter_column('invitation_code_uses', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    safe_drop_index('ix_invitation_code_uses_code_id', table_name='invitation_code_uses')
    safe_drop_index('ix_invitation_code_uses_user_id', table_name='invitation_code_uses')
    op.alter_column('invitation_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    safe_drop_constraint('invitation_codes_code_key', 'invitation_codes', type_='unique')
    safe_drop_index('ix_invitation_codes_organization_id', table_name='invitation_codes')
    op.alter_column('online_platforms', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('online_platforms', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    safe_drop_index('ix_online_platforms_branch_id', table_name='online_platforms')
    safe_drop_constraint('online_platforms_branch_id_fkey', 'online_platforms', type_='foreignkey')
    op.create_foreign_key(None, 'online_platforms', 'branches', ['branch_id'], ['id'])
    op.alter_column('online_sales', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    safe_drop_constraint('organizations_code_key', 'organizations', type_='unique')
    safe_drop_index('ix_purchase_product_groups_branch_id', table_name='purchase_product_groups')
    safe_drop_constraint('purchase_product_groups_branch_id_fkey', 'purchase_product_groups', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_product_groups', 'branches', ['branch_id'], ['id'])
    safe_drop_index('ix_purchase_products_branch_id', table_name='purchase_products')
    safe_drop_constraint('purchase_products_branch_id_fkey', 'purchase_products', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_products', 'branches', ['branch_id'], ['id'])
    op.alter_column('user_branches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    safe_drop_constraint('uq_user_branch', 'user_branches', type_='unique')
    safe_drop_index('ix_users_google_id', table_name='users')
    safe_drop_index('ix_users_organization_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_organization_id', 'users', ['organization_id'], unique=False)
    op.create_index('ix_users_google_id', 'users', ['google_id'], unique=True)
    op.create_unique_constraint('uq_user_branch', 'user_branches', ['user_id', 'branch_id'])
    op.alter_column('user_branches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'purchase_products', type_='foreignkey')
    op.create_foreign_key('purchase_products_branch_id_fkey', 'purchase_products', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_purchase_products_branch_id', 'purchase_products', ['branch_id'], unique=False)
    op.drop_constraint(None, 'purchase_product_groups', type_='foreignkey')
    op.create_foreign_key('purchase_product_groups_branch_id_fkey', 'purchase_product_groups', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_purchase_product_groups_branch_id', 'purchase_product_groups', ['branch_id'], unique=False)
    op.create_unique_constraint('organizations_code_key', 'organizations', ['code'])
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('online_sales', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'online_platforms', type_='foreignkey')
    op.create_foreign_key('online_platforms_branch_id_fkey', 'online_platforms', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_online_platforms_branch_id', 'online_platforms', ['branch_id'], unique=False)
    op.alter_column('online_platforms', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('online_platforms', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_invitation_codes_organization_id', 'invitation_codes', ['organization_id'], unique=False)
    op.create_unique_constraint('invitation_codes_code_key', 'invitation_codes', ['code'])
    op.alter_column('invitation_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_invitation_code_uses_user_id', 'invitation_code_uses', ['user_id'], unique=False)
    op.create_index('ix_invitation_code_uses_code_id', 'invitation_code_uses', ['code_id'], unique=False)
    op.alter_column('invitation_code_uses', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_import_history_items_history', 'import_history_items', ['import_history_id'], unique=False)
    op.create_index('ix_import_history_branch_date', 'import_history', ['branch_id', 'import_date'], unique=False)
    op.drop_constraint(None, 'expense_categories', type_='foreignkey')
    op.create_foreign_key('expense_categories_branch_id_fkey', 'expense_categories', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_expense_categories_branch_id', 'expense_categories', ['branch_id'], unique=False)
    op.create_unique_constraint('daily_insights_branch_id_date_key', 'daily_insights', ['branch_id', 'date'])
    op.alter_column('daily_insights', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_cash_differences_difference_date'), table_name='cash_differences')
    op.create_unique_constraint('uq_cash_diff_branch_date', 'cash_differences', ['branch_id', 'difference_date'])
    op.create_index('ix_cash_differences_status', 'cash_differences', ['status'], unique=False)
    op.create_index('ix_cash_differences_date', 'cash_differences', ['difference_date'], unique=False)
    op.alter_column('cash_differences', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'ok'::character varying"))
    op.alter_column('cash_differences', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('cash_differences', 'pos_total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'pos_migros',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'pos_yemeksepeti',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'pos_getir',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'pos_trendyol',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'pos_nakit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'pos_visa',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'kasa_total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'kasa_migros',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'kasa_yemeksepeti',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'kasa_getir',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'kasa_trendyol',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'kasa_nakit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cash_differences', 'kasa_visa',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.create_index('ix_cdi_platform_source', 'cash_difference_items', ['platform_id', 'source_type'], unique=False)
    op.create_index('ix_cdi_cash_difference_id', 'cash_difference_items', ['cash_difference_id'], unique=False)
    op.create_index('ix_branches_organization_id', 'branches', ['organization_id'], unique=False)
    op.drop_table('supplier_transactions')
    op.drop_table('supplier_payments')
    # ### end Alembic commands ###
