"""add record_type to monthly_payrolls

Revision ID: 50070868fced
Revises: f35e4ae3cfd2
Create Date: 2025-12-16 19:32:15.586855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50070868fced'
down_revision: Union[str, None] = 'f35e4ae3cfd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Önce nullable olarak ekle
    op.add_column('monthly_payrolls', sa.Column('record_type', sa.String(length=20), nullable=True))

    # Mevcut kayıtlar için default değer ata
    op.execute("UPDATE monthly_payrolls SET record_type = 'salary' WHERE record_type IS NULL")

    # NOT NULL yap
    op.alter_column('monthly_payrolls', 'record_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthly_payrolls', 'record_type')
    # ### end Alembic commands ###
