"""add_purchase_product_groups_and_products

Revision ID: e0f4cfec45fd
Revises: 8774f956b692
Create Date: 2025-12-16 18:16:19.478576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f4cfec45fd'
down_revision: Union[str, None] = '8774f956b692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_product_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_unit', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['purchase_product_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('purchase_items', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase_items', 'purchase_products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_items', type_='foreignkey')
    op.drop_column('purchase_items', 'product_id')
    op.drop_table('purchase_products')
    op.drop_table('purchase_product_groups')
    # ### end Alembic commands ###
