"""add payment_date to monthly_payrolls

Revision ID: f35e4ae3cfd2
Revises: a7e0db958ef1
Create Date: 2025-12-16 19:23:50.196022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f35e4ae3cfd2'
down_revision: Union[str, None] = 'a7e0db958ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # İlk önce nullable olarak ekle
    op.add_column('monthly_payrolls', sa.Column('payment_date', sa.Date(), nullable=True))

    # Mevcut kayıtlar için created_at tarihini kullan
    op.execute("UPDATE monthly_payrolls SET payment_date = created_at::date WHERE payment_date IS NULL")

    # Artık NOT NULL yapabiliriz
    op.alter_column('monthly_payrolls', 'payment_date', nullable=False)

    op.create_index(op.f('ix_monthly_payrolls_payment_date'), 'monthly_payrolls', ['payment_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_payrolls_payment_date'), table_name='monthly_payrolls')
    op.drop_column('monthly_payrolls', 'payment_date')
    # ### end Alembic commands ###
